spring:
  datasource:
    url: jdbc:mysql://rm-bp1g480vjp87558694o.mysql.rds.aliyuncs.com:3306/tomato?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: valorant
    password: tomatomall_12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24小时

server:
  port: 8080

logging:
  level:
    root: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.example.tomatomall: INFO
    com.zaxxer.hikari: WARN
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: WARN
    org.springframework.boot.autoconfigure: WARN
    org.springframework.boot.diagnostics: WARN

aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    accessKeyId: LTAI5tQjoMbKFGEUonEhyJww
    accessKeySecret: qLAz9MfZo0LIJNpFMKIpJLjiNL7jOz
    bucketName: blue-whale-231250120

alipay:
  app-id: 2021000148605923
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDATHDdsgD1ZNVxwwKR7t5HwaaSDy8B2j4qHmKFSYBO2CYoERXIc2xWTY1l69eCX4uDBmZZvLi+6KtMsYQpRQyczERLC5e7RFJuLgbybj/gWj+cS6T8AqkgzWD8Wdyyo6Y+/PsyTass9J9nMfjgFAxuuQpYyYg+dcCprEzhz/rdzSK5vHPiZR6GnDGadQwe7uXlCLQGf/EOK1qEiIOJPaq3jZC1stqzwU4bRuJIfkmtAwOBvO68g32k9GDVJudppt/qKtzdMD8OMUHaeK4UjUjozmTATmRYqRRRC83uDFI2dzw73wEIwjtmv9NYsx/MyPE2sWD9MTnnTRLHyuwtilwtAgMBAAECggEAa+27X0Kb9R8eCVapZ5zI1z9iLRImkQSb5WneY+7H+/inGc/VCQd3Y8ztMqo27+6OUADUi0M38baHBmmPwtYFaS/gmLot9CY5mattrL2iTlp431E5jVQ09rsu1xPcocrl8O5uUmJzU60Mlo/enm3COJbUrtaWCHBwrQqOsCLaK4gQmJXQTy02bf9qUawmE7Ekih243OsnbZmSMAF27xecCPRGU+WyTeZiOvA4Qu7Z6lXxLHZKVoqOEZm1OY662UcFm+jl3+zTyRIOqlHJyd5Gi9vi6RAIqTZGuEevnvzGL8YK8wGHs+VopsIXQQlwIpzXCfrzxqeHgJFod1KDYyw4oQKBgQDrcIk+Yh7jNcvMBwtvfn9Hb+KkK+uCj4lDdQB8WzkTvIlsWZEY+xOwLZr8CEeKZA3lQS42oGVMYN+kb1i/RCy1Gtxqxi9/Hl+faSqQdgPA04PblMuFgjFtsr5BL5uBOy0WNQaKZWZ5jbjL3b5D3RBgiDaQ6/eM//+eYJNxctPe1QKBgQDRF3LwpgGjp5NA13uDljCTeS0yIEZFd/5bVrCsX0g5Pizsk48dGT1gVuZKS8XwGWqhOYLRxYTIHDXRGBYTbyWdOnR7bJFo7w+11G30q6t4qNIV05wxIMNU3YzZaiYIYl5jrsYSJL05ej6d1mqhbrjvu2BOCMfwNBjPno+JOMGj+QKBgQCi9ifoyB29AtVnCVE/AP20QptLKyM+IX/O80M80B93q74rAuvNsKv1+/sUi96IyaxcjHsiUG8NKNhjhraU3OldCZSbS0ZA5JMnUbGmgCkk5MKV0C324SC5X0kU8ZDfKEiS4G0AiiMd65yHb5pseq0FRAMQ2GNmcyNJSmuD0QkZaQKBgFe/HnZNRFzYo1xP0b68FbCd5tClaLgYjj7ol4YPCnEzXYj+t81/XRmD/mrpd6y2DeCREQxVds6/v/n6wLDxMPjVojJ1smQ2BwLInkhSjsg5GMkeH+siE7cWrthCyqk0FuaAXxEYJ+zqF0MHy4HpxGSe3uCAoN92DX97zELK9cCJAoGANHxVj+Gs8cS4DgdIi2VqgDHulxpmiOhy/1wHorOhQ3hAhK7IZx/eFhdJA+q27+qbc6L7VJqz7y+ZlNzV4NTyOoK6+pProqerZEzDG3f793zYx8mJdamHM+CU7DSVQraJEm2syn9nmydFJN1OHucCj/QqgKqpAnjVeqAU158q2C4=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAre7Oxxb0V3TLI8vKm2/tPIXOb2Lrve74THGKu2SRHdoKZlePdtOlZy9hwDx/bcItxOTE42viNDqlcR4erDABB+l3HwHUgZQ+Zngik/T5uYe5bkQdJLE2iXDydGKOEA0lYPbwT1h35wFfbRQIxpeyIRPmA0W6vgNu6Kp8ZFllrLeeQNBakKhhSEar/u626N2lMuZzmS/5x4Ljn+4NJif+3KULSTxiuCeVly4XI/vu/poSq9bLLaX9teWMH04NTYxNmmPyUWsYK/1gI/6O8wRcPdFFPrRpu2Kpz0RZbwICMDLuMYUFQMLkqJzYGIzdBtb+69An+BP7xnog1e8ncBrcMQIDAQAB
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: utf-8
  sign-type: RSA2
  notify-url: https://stinkbug-perfect-lynx.ngrok-free.app/api/orders/notify
  return-url: http://localhost:5173/orders
