spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/tomato?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: valorant
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24小时

server:
  port: 8080

logging:
  level:
    root: OFF
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com.example.tomatomall: OFF
    com.zaxxer.hikari: INFO
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: INFO

aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    accessKeyId: LTAI5tQjoMbKFGEUonEhyJww
    accessKeySecret: qLAz9MfZo0LIJNpFMKIpJLjiNL7jOz
    bucketName: blue-whale-231250120